version: 0.2

phases:
  pre_build:
    commands:
      # login to ECR
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      # get commit hash
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      # build go app with static lin
      # build lightweight app image which only contains the binary
      - docker build . -t $ECR_REPO/$SERVICE:$COMMIT_HASH
      # tag image
      
  post_build:
    commands:
      # push to ECR
      - docker push $ECR_REPO/$SERVICE:$COMMIT_HASH

