version: 0.2

phases:
  pre_build:
    commands:
      # download and configure AWS IAM Authenticator
      - curl  -L  -o /usr/local/bin/kubectl  https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl
      - curl -o /usr/local/bin/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.5/2018-12-06/bin/linux/amd64/aws-iam-authenticator
      - chmod 755 /usr/local/bin/aws-iam-authenticator
      - chmod 755 /usr/local/bin/kubectl
      # update kube config
      - aws eks --region us-east-1 update-kubeconfig --name demo
      # get commit hash
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      # create namespace
      - kubectl create ns $EKS_NAMESPACE || true
      # set current namespace
      - kubectl config set-context $(kubectl config current-context) --namespace=$EKS_NAMESPACE
      # update image in deployment
      -  kubectl set image deployment/$SERVICE $SERVICE=$ECR_REPO/$SERVICE:$COMMIT_HASH --record
